Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\rmacharia\Documents\mybusiness\avertis work papers\Geonet-ERP-master\warehouse module\myapp\warehouse\views.py", line 69, in home
    return render_template("warehouse/home.html")
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\rmacharia\Documents\mybusiness\avertis work papers\Geonet-ERP-master\warehouse module\myapp\warehouse\templates\warehouse\home.html", line 1, in top-level template code
    {% extends "warehouse/base.html" %}
  File "C:\Users\rmacharia\Documents\mybusiness\avertis work papers\Geonet-ERP-master\warehouse module\myapp\warehouse\templates\warehouse\base.html", line 32, in top-level template code
    <a href="{{ url_for("projects.home") }}" class="nav-link">Home</a>
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\helpers.py", line 323, in url_for
    force_external=external)
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\routing.py", line 1768, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'projects.home'. Did you mean 'warehouse.home' instead?
Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\rmacharia\Documents\mybusiness\avertis work papers\Geonet-ERP-master\warehouse module\myapp\warehouse\views.py", line 69, in home
    return render_template("warehouse/home.html")
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\rmacharia\Documents\mybusiness\avertis work papers\Geonet-ERP-master\warehouse module\myapp\warehouse\templates\warehouse\home.html", line 1, in top-level template code
    {% extends "warehouse/base.html" %}
  File "C:\Users\rmacharia\Documents\mybusiness\avertis work papers\Geonet-ERP-master\warehouse module\myapp\warehouse\templates\warehouse\base.html", line 33, in top-level template code
    <a href="{{ url_for("projects.home") }}" class="nav-link">Home</a>
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\helpers.py", line 323, in url_for
    force_external=external)
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\routing.py", line 1768, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'projects.home'. Did you mean 'warehouse.home' instead?
Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\rmacharia\Documents\mybusiness\avertis work papers\Geonet-ERP-master\warehouse module\myapp\warehouse\views.py", line 69, in home
    return render_template("warehouse/home.html")
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\rmacharia\Documents\mybusiness\avertis work papers\Geonet-ERP-master\warehouse module\myapp\warehouse\templates\warehouse\home.html", line 1, in top-level template code
    {% extends "warehouse/base.html" %}
  File "C:\Users\rmacharia\Documents\mybusiness\avertis work papers\Geonet-ERP-master\warehouse module\myapp\warehouse\templates\warehouse\base.html", line 70, in top-level template code
    {% block content %}
  File "C:\Users\rmacharia\Documents\mybusiness\avertis work papers\Geonet-ERP-master\warehouse module\myapp\warehouse\templates\warehouse\home.html", line 3, in block "content"
    {% include warehouse/inventory.html%}
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'inventory' is undefined
Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\rmacharia\Documents\mybusiness\avertis work papers\Geonet-ERP-master\warehouse module\myapp\warehouse\views.py", line 69, in home
    return render_template("warehouse/home.html")
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\rmacharia\Documents\mybusiness\avertis work papers\Geonet-ERP-master\warehouse module\myapp\warehouse\templates\warehouse\home.html", line 1, in top-level template code
    {% extends "warehouse/base.html" %}
  File "C:\Users\rmacharia\Documents\mybusiness\avertis work papers\Geonet-ERP-master\warehouse module\myapp\warehouse\templates\warehouse\base.html", line 70, in top-level template code
    {% block content %}
  File "C:\Users\rmacharia\Documents\mybusiness\avertis work papers\Geonet-ERP-master\warehouse module\myapp\warehouse\templates\warehouse\home.html", line 3, in block "content"
    {% include "warehouse/inventory.html" %}
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\rmacharia\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: warehouse/inventory.html
